Module 01: Exploratory Data Analysis for Demand & Inventory with Polars

This notebook performs exploratory data analysis (EDA) for Module 01 of the **"Intelligent System for Supply Chain Management"** project.  

The primary goal is to optimize inventory and purchasing management, with a target of **reducing overstocking by 20%** within six months.

---

## Import Libraries

In [2]:
import polars as pl
import polars.selectors as cs
import json
import plotly.express as px
import plotly.io as pio
from pathlib import Path
from polars_info import print_df_info
from datetime import date

# Install dependencies as needed:
# pip install kagglehub[polars-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

import warnings
warnings.filterwarnings('ignore')

# Set up display options and plotting template
pio.templates.default = "plotly_white"
px.defaults.width = 800
px.defaults.height = 600

## Load Dataset

In [3]:
# Paths
path_docs = Path("..") / "docs"
path_processed = Path("..") / "data" / "processed"

In [4]:
# Set the path to the file you'd like to load
file_path = "1M_grocery_data_pl.parquet"

# Load the latest version
lf = kagglehub.dataset_load(
  KaggleDatasetAdapter.POLARS,
  "robertobalbinotti/synthetic-grocery-data",
  file_path,
  # Provide any additional arguments like
  # sql_query, polars_frame_type, or 
  # polars_kwargs.
  # See the documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpolars
)

In [9]:
# Load column descriptions from JSON file into a dictionary for reference or documentation
with open(path_docs / 'column_descriptions_polars.json') as f:
    column_descriptions = json.load(f)

# Data Cleaning and Preprocessing

In [11]:
print_df_info(lf.collect())

<class 'polars.dataframe.frame.DataFrame'>
Shape: (1,000,658, 31)
Estimated size: 182.25 MiB
Columns:
  #  Column                        Dtype         Non-Null    Null   Null%
  0  order_purchase_date           Date          1,000,658       0   0.00%
  1  received_date                 Date          1,000,658       0   0.00%
  2  product_id                    String        1,000,658       0   0.00%
  3  product                       String        1,000,658       0   0.00%
  4  category                      String        1,000,658       0   0.00%
  5  sub_category                  String        1,000,658       0   0.00%
  6  sales_demand                  String        1,000,658       0   0.00%
  7  sales_volume                  UInt16        1,000,658       0   0.00%
  8  seasonality                   List(String)  1,000,658       0   0.00%
  9  storage_recommendation        String        1,000,658       0   0.00%
 10  unit_of_measurement           String        1,000,658       0   0.00%
 11  shelf_life_days               UInt16        1,000,658       0   0.00%
 12  maximum_days_on_sale          UInt16        1,000,658       0   0.00%
 13  supplier_id                   String        1,000,658       0   0.00%
 14  supplier                      String        1,000,658       0   0.00%
 15  supplier_rating               UInt8         1,000,658       0   0.00%
 16  distance_km                   UInt16        1,000,658       0   0.00%
 17  moq                           UInt16        1,000,658       0   0.00%
 18  delivery_days                 Float16       1,000,658       0   0.00%
 19  transit_time                  Float16       1,000,658       0   0.00%
 20  in_season                     Boolean       1,000,658       0   0.00%
 21  is_holiday                    Boolean       1,000,658       0   0.00%
 22  day_classification            String        1,000,658       0   0.00%
 23  is_weekend                    Boolean       1,000,658       0   0.00%
 24  min_stock                     UInt16        1,000,658       0   0.00%
 25  max_stock                     UInt16        1,000,658       0   0.00%
 26  stock_quantity                UInt16        1,000,658       0   0.00%
 27  temperature_classification    String        1,000,658       0   0.00%
 28  precipitation_classification  String        1,000,658       0   0.00%
 29  wind_classification           String        1,000,658       0   0.00%
 30  weather_severity              String        1,000,658       0   0.00%

DFInfoSummary(rows=1000658, cols=31, estimated_size_bytes=191102740, dtypes={'order_purchase_date': Date, 'received_date': Date, 'product_id': String, 'product': String, 'category': String, 'sub_category': String, 'sales_demand': String, 'sales_volume': UInt16, 'seasonality': List(String), 'storage_recommendation': String, 'unit_of_measurement': String, 'shelf_life_days': UInt16, 'maximum_days_on_sale': UInt16, 'supplier_id': String, 'supplier': String, 'supplier_rating': UInt8, 'distance_km': UInt16, 'moq': UInt16, 'delivery_days': Float16, 'transit_time': Float16, 'in_season': Boolean, 'is_holiday': Boolean, 'day_classification': String, 'is_weekend': Boolean, 'min_stock': UInt16, 'max_stock': UInt16, 'stock_quantity': UInt16, 'temperature_classification': String, 'precipitation_classification': String, 'wind_classification': String, 'weather_severity': String})

In [12]:
df = lf.with_columns(
    pl.col(pl.Utf8).cast(pl.Categorical()),
).collect()

In [14]:
received_date = df.select("received_date").to_series().sort().unique()

expected_date_range = pl.date_range(
    start= received_date.min(),
    end= received_date.max(),
    interval="1d",
    eager=True
)

is_complete = received_date.len() == expected_date_range.len()
missing_dates = expected_date_range.filter(~expected_date_range.is_in(received_date))

print("Complete Received Date Range?\n", is_complete)
missing_dates

Complete Received Date Range?
 True

shape: (0,)
Series: 'literal' [date]
[
]

In [26]:
df.filter(
    pl.struct(['order_purchase_date', 'received_date', 'product_id', 'supplier_id']).is_duplicated()
)

shape: (802_870, 31)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ order_pur ┆ received_ ┆ product_i ┆ product   ┆ … ┆ temperatu ┆ precipita ┆ wind_clas ┆ weather_ │
│ chase_dat ┆ date      ┆ d         ┆ ---       ┆   ┆ re_classi ┆ tion_clas ┆ sificatio ┆ severity │
│ e         ┆ ---       ┆ ---       ┆ cat       ┆   ┆ fication  ┆ sificatio ┆ n         ┆ ---      │
│ ---       ┆ date      ┆ cat       ┆           ┆   ┆ ---       ┆ n         ┆ ---       ┆ cat      │
│ date      ┆           ┆           ┆           ┆   ┆ cat       ┆ ---       ┆ cat       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ cat       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2022-12-0 ┆ 2022-12-0 ┆ 1169187|P ┆ Tomato    ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 7         ┆ 9         ┆           ┆           ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2022-12-0 ┆ 2022-12-0 ┆ 1741974|P ┆ Mozzarell ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 6         ┆ 9         ┆           ┆ a Cheese  ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2022-12-0 ┆ 2022-12-0 ┆ 1113278|P ┆ Carrot    ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 6         ┆ 9         ┆           ┆           ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2022-12-0 ┆ 2022-12-0 ┆ 1202127|P ┆ Pomegrana ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 6         ┆ 9         ┆           ┆ te        ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2022-12-0 ┆ 2022-12-0 ┆ 1821093|P ┆ Grape     ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 7         ┆ 9         ┆           ┆ Jelly     ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-09-1 ┆ 2025-09-2 ┆ 1230940|P ┆ Haddock   ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 9         ┆ 2         ┆           ┆           ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2025-09-1 ┆ 2025-09-2 ┆ 1385860|P ┆ Granola   ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 8         ┆ 2         ┆           ┆ Bars      ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2025-09-2 ┆ 2025-09-2 ┆ 1543068|P ┆ Rye Bread ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 0         ┆ 2         ┆           ┆           ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2025-09-2 ┆ 2025-09-2 ┆ 1677266|P ┆ Pork      ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 0         ┆ 2         ┆           ┆ Chops     ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2025-09-2 ┆ 2025-09-2 ┆ 1932636|P ┆ Bread     ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 0         ┆ 2         ┆           ┆ Flour     ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
df.filter(
    ~pl.struct([
        'order_purchase_date', 
        'received_date', 
        'product_id', 
        'supplier_id'
    ]).is_duplicated()
)

shape: (197_788, 31)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ order_pur ┆ received_ ┆ product_i ┆ product   ┆ … ┆ temperatu ┆ precipita ┆ wind_clas ┆ weather_ │
│ chase_dat ┆ date      ┆ d         ┆ ---       ┆   ┆ re_classi ┆ tion_clas ┆ sificatio ┆ severity │
│ e         ┆ ---       ┆ ---       ┆ cat       ┆   ┆ fication  ┆ sificatio ┆ n         ┆ ---      │
│ ---       ┆ date      ┆ cat       ┆           ┆   ┆ ---       ┆ n         ┆ ---       ┆ cat      │
│ date      ┆           ┆           ┆           ┆   ┆ cat       ┆ ---       ┆ cat       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ cat       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2022-12-0 ┆ 2022-12-0 ┆ 1234660|P ┆ Butter    ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 5         ┆ 9         ┆           ┆           ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2022-12-0 ┆ 2022-12-0 ┆ 1476237|P ┆ Canned    ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 6         ┆ 9         ┆           ┆ Tuna      ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2022-12-0 ┆ 2022-12-0 ┆ 1457947|P ┆ Egg       ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 5         ┆ 9         ┆           ┆ (Quail)   ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2022-12-0 ┆ 2022-12-0 ┆ 1659804|P ┆ Honey     ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 6         ┆ 9         ┆           ┆           ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2022-12-0 ┆ 2022-12-0 ┆ 1606966|P ┆ Shrimp    ┆ … ┆ Warm      ┆ No precip ┆ Gentle to ┆ Moderate │
│ 8         ┆ 9         ┆           ┆           ┆   ┆           ┆ itation   ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-09-1 ┆ 2025-09-2 ┆ 1921785|P ┆ Raw Sugar ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 9         ┆ 2         ┆           ┆           ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2025-09-1 ┆ 2025-09-2 ┆ 1606966|P ┆ Shrimp    ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 8         ┆ 2         ┆           ┆           ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2025-09-2 ┆ 2025-09-2 ┆ 1060542|P ┆ Strawberr ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 1         ┆ 2         ┆           ┆ ies       ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2025-09-2 ┆ 2025-09-2 ┆ 1122425|P ┆ Sugar     ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 1         ┆ 2         ┆           ┆           ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
│ 2025-09-2 ┆ 2025-09-2 ┆ 1234660|P ┆ Butter    ┆ … ┆ Mild to   ┆ Heavy     ┆ Gentle to ┆ Severe   │
│ 1         ┆ 2         ┆           ┆           ┆   ┆ Temperate ┆ Rain      ┆ Fresh     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Breeze    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
df.columns

['order_purchase_date',
 'received_date',
 'product_id',
 'product',
 'category',
 'sub_category',
 'sales_demand',
 'sales_volume',
 'seasonality',
 'storage_recommendation',
 'unit_of_measurement',
 'shelf_life_days',
 'maximum_days_on_sale',
 'supplier_id',
 'supplier',
 'supplier_rating',
 'distance_km',
 'moq',
 'delivery_days',
 'transit_time',
 'in_season',
 'is_holiday',
 'day_classification',
 'is_weekend',
 'min_stock',
 'max_stock',
 'stock_quantity',
 'temperature_classification',
 'precipitation_classification',
 'wind_classification',
 'weather_severity']